# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow file requires a free account on Semgrep.dev to
# manage rules, file ignores, notifications, and more.
#
# See https://semgrep.dev/docs

name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '32 4 * * 6'
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout project source
      - uses: actions/checkout@v4

      # 2. Scan code and generate the SARIF file
      - uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"
          config: "p/default p/security-audit p/owasp-top-10 p/cwe-top-25"

      # 3. Upload SARIF to GitHub Security Dashboard (Code scanning)
      - name: Upload SARIF to Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()

      # 4. Force save the file as a downloadable GitHub Action Artifact
      - name: Save SARIF as Downloadable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-file
          path: semgrep.sarif
        if: always()

